ServerPort: 8080 #Http port
EnableTLS: false #Enable https ( configure also  CertPathCrt and CertPathKey)
DisableNoTLS: false #Disable non https connection, (Plese, set EnableTLS as true, CertPathCrt and CertPathKey)
ServerPortTLS: 10443 #Https port
CertPathCrt: "./cert/full-cert.crt"
CertPathKey: "./cert/private-key.key"
Key: 12345 
DisableWOLWithoutusername: false #Allow only WOL using username (]/sendWOLuser?user=[username]) and not by MAC (sendWOL?mac=[macadress])
